export const PROMPT_PLACEHOLDER_IDEAS = [
	'sushi styled website with pastel colors and modern design',
	'futuristic tech blog with dark mode',
	'cozy coffee shop website with warm tones',
	'minimalist portfolio website with smooth scrolling',
	'fitness app landing page with bold typography',
	'luxury hotel landing page with elegant animations',
	'children’s educational landing page with playful illustrations',
	'photography portfolio SPA with interactive gallery',
	'handmade crafts shop landing page with pastel palette',
	'recipe landing page with scrolling recipe sections',
	'music festival landing page with vibrant animations',
	'fashion brand single-page website with parallax effects',
	'yoga studio landing page with calm colors and sectioned schedule',
	'science blog landing page with interactive charts in sections',
	'podcast landing page with dynamic episode previews',
	'travel destination SPA with full-screen image sections',
	'mobile app promo landing page with animated feature highlights',
	'tech startup landing page with smooth scrolling and gradient sections',
	'real estate property landing page with interactive property sections',
	'restaurant menu SPA with scrolling menu categories',
	'art gallery single-page website with sliding exhibitions',
	'online course landing page with sectioned curriculum',
	'fashion store landing page with product showcase animations',
	'event landing page with countdown timer and RSVP sections',
	'personal blog SPA with smooth scrolling and illustrations',
	'startup SaaS landing page with feature highlights',
	'charity landing page with donation sections',
	'local cafe landing page with menu and reservation sections',
	'fitness trainer landing page with video sections',
	'book review SPA with interactive ratings',
	'movie streaming promo landing page with trailers',
	'pet adoption landing page with filterable profiles',
	'travel agency landing page with interactive destinations',
	'coffee subscription landing page with animated benefits',
	'tech conference landing page with speaker highlights',
	'food delivery landing page with sectioned menus',
	'online portfolio SPA with project carousel',
	'craft beer brewery landing page with interactive history',
	'startup incubator landing page with team section',
	'yoga retreat landing page with schedule and booking',
	'photography contest landing page with voting sections',
	'charity fundraising landing page with donation tracker',
	'online recipe SPA with step-by-step sections',
	'gaming tournament landing page with leaderboard',
	'music album promo landing page with track previews',
	'local event landing page with map sections',
	'startup product landing page with feature highlights',
	'education platform SPA with course sections',
	'fashion influencer landing page with gallery',
	'virtual art exhibition landing page with interactive navigation',
	'podcast network landing page with episode highlights',
	'travel blog SPA with destination stories',
	'coffee shop landing page with menu and gallery sections',
	'fitness challenge landing page with progress tracker',
	'tech product landing page with feature animations',
	'handmade jewelry landing page with product carousel',
	'movie festival landing page with schedule and highlights',
	'local restaurant landing page with menu and reviews',
	'online workshop landing page with registration sections',
	'startup portfolio SPA with case studies',
	'art class landing page with schedule and gallery',
	'charity campaign landing page with milestones and stories',
	'fashion boutique landing page with product highlights',
	'yoga class landing page with interactive timetable',
	'food blog landing page with recipe categories',
	'travel guide SPA with map and tips',
	'gaming app landing page with animated features',
	'online photography course landing page with lesson sections',
	'fitness equipment landing page with sectioned features',
	'music festival landing page with schedule and performers',
	'coffee shop landing page with promotions and gallery',
	'tech tutorial SPA with sectioned lessons',
	'startup demo landing page with feature highlights',
	'crafts marketplace landing page with product categories',
	'bookstore landing page with new arrivals and sections',
	'online learning SPA with courses and progress tracker',
	'podcast series landing page with dynamic episodes',
	'art studio SPA with class schedule and portfolio',
	'food delivery SPA with animated menu sections',
	'local events landing page with RSVP sections',
	'mobile game landing page with feature previews',
	'fashion magazine SPA with article sections',
	'tech product SPA with interactive features',
	'charity SPA with donation tracker and stories',
	'online portfolio landing page with smooth scrolling',
	'music band landing page with tour and album sections'
];
